In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# 1. 读入初步处理好的数据
df_data = pd.read_csv('初步处理data_0119.csv')
df_data.head() # 查看头五行

,Unnamed: 0,Anon Student Id,Student Response Subtype,Duration (sec),Outcome
0,1,Stu_11eed491c49d08923078a99c3689faa6,Axes,17.5,CORRECT
1,3,Stu_11eed491c49d08923078a99c3689faa6,NextStepHelp,74,HINT
2,6,Stu_11eed491c49d08923078a99c3689faa6,NextStepHelp,57,HINT
3,7,Stu_11eed491c49d08923078a99c3689faa6,Explain-Further,4,HINT
4,9,Stu_11eed491c49d08923078a99c3689faa6,Axes,21.5,INCORRECT

In [4]:
# 2. 打印一个学生的数据观察
single_stu_df = df_data[df_data['Anon Student Id'] == 'Stu_11eed491c49d08923078a99c3689faa6']
single_stu_df.groupby("Student Response Subtype").agg('sum')

                          Unnamed: 0
Student Response Subtype
Answer                        135810
Axes                           68385
Choose-Principle              108784
Choose-Sought                 126621
Equation                      524816
Explain-Further              2485795
NextStepHelp                  898351
Variable                      319059
Whats-Wrong                   105222

In [5]:
# 3. 查看有多少学生
stu_count_df = df_data.drop_duplicates(subset = ['Anon Student Id', ], keep = 'first', inplace=False)
print("总共有{}个学生。".format(len(stu_count_df)))
stu_count_df

总共有69个学生。

,Unnamed: 0,Anon Student Id,Student Response Subtype,Duration (sec),Outcome
0,1,Stu_11eed491c49d08923078a99c3689faa6,Axes,17.5,CORRECT
2726,3400,Stu_16d36e81d1d34630d27d8fd8b9d99d53,NextStepHelp,8,HINT
6687,8266,Stu_1712d2d13ed773fddf0c9a59ad099b21,Axes,73,INCORRECT
6702,8304,Stu_18d58be83dc070054ca65038cc2293b4,Axes,37,CORRECT
8016,9908,Stu_1a24bc4f1db0936c28f45176d3c425a7,Axes,6.5,CORRECT
...,...,...,...,...,...
120954,159329,Stu_f8258e6b33109ea4808c004915145dd2,Answer,18,INCORRECT
123596,162961,Stu_fa1d7f2f99f036137482fbc04bab625b,NextStepHelp,46,HINT
126132,166032,Stu_fb6121b7f70cc8dc2dca6a97e2c7cdc5,Whats-Wrong,2,HINT
129457,170138,Stu_fd75420a601b7a43d13ea33ce657a2e1,Equation,90,INCORRECT
129625,170369,Stu_ff13c22bdf5c4eb4fa87e03fe5d782ad,Whats-Wrong,3,HINT

**4. 接下来将计算每个学生的每个行为的持续性时间，每个行为的频次，正确率**
<br>

|  行为 | Behavior  |指标|
|  ----  | ----  | ----  |
|绘制/生成坐标|Axes|（时间，频次，正确率）|
|绘制向量|Vector|（时间，频次，正确率）|
|定义变量|Variable|（频次，正确率）|
|公式推导|Equation|（时间，频次，正确率）|
|查看资料|Choose-Principle|（频次）|
|回答问题|Answer|（时间，频次，正确率）|
|错题订正|Whats-Wrong|（频次）|
|尝试提交|Solve|（频次）|

<br><br>
事先说明一下，最后处理出来的每个学生的信息是一个八个维度的向量：
<br>
stu_demo = (Axes, Vector, Variable, Equation, Choose-Principle, Answer, Whats-Wrong, Solve)

In [47]:
# 4.1 首先，我们提取一个包含所有学生的列表；因为接下来要分别对每个学生统计以上数据。
temp_li = [] # 暂时用来存每个学生的DataFrame
stu_list=stu_count_df['Anon Student Id'].values.tolist()
for stu,i in zip(stu_list, range(len(stu_list))):
    single_stu_df = df_data[df_data['Anon Student Id'] == stu]
    # 统计频次
    count_srs = single_stu_df.groupby("Student Response Subtype").agg('count')
    
    # 然后将每种学习行为和频次用键值对（字典）一一对应起来，顺便把学生的 ID：‘@#￥%@’ 这样的加入字典
    # 学习行为(因为有些学生的某些学习行为是没有的，所以需要单独提取出来)
    stu_study_behav = list(count_srs.index)
    stu_study_behav.insert(0, 'Anon Student Id')
    
    # 学习行为对应的频次(加入学生ID)
    stu_behavior_freq = list(count_srs['Anon Student Id'])
    stu_behavior_freq.insert(0, stu)
    
    # 将“学习行为字段”和“学习行为频次”组成字典
    single_stu_temp_dict = dict(zip(stu_study_behav, stu_behavior_freq))
    
    # 然后根据字典生成当前学生的DataFrame
    single_stu_df_processed = pd.DataFrame(single_stu_temp_dict, index = [0])
    temp_li.append(single_stu_df_processed)

In [51]:
# 将所有学生的学习行为频次组合起来
all_stu_behav = pd.concat(temp_li)
# 将缺失值补充为0
all_stu_behav = all_stu_behav.fillna(0)
# 保存为CSV
all_stu_behav.to_csv("学生频次数据_0120.csv")

all_stu_behav

,Anon Student Id,Answer,Axes,Choose-Principle,Choose-Sought,Equation,Explain-Further,NextStepHelp,Variable,Whats-Wrong
0,Stu_11eed491c49d08923078a99c3689faa6,82.0,51.0,62.0,77.0,312.0,1421.0,505.0,147.0,69.0
0,Stu_16d36e81d1d34630d27d8fd8b9d99d53,99.0,57.0,77.0,87.0,436.0,2138.0,818.0,212.0,37.0
0,Stu_1712d2d13ed773fddf0c9a59ad099b21,0.0,3.0,0.0,0.0,0.0,7.0,1.0,0.0,4.0
0,Stu_18d58be83dc070054ca65038cc2293b4,69.0,34.0,33.0,31.0,156.0,642.0,247.0,68.0,34.0
0,Stu_1a24bc4f1db0936c28f45176d3c425a7,15.0,40.0,46.0,42.0,462.0,436.0,247.0,160.0,92.0
...,...,...,...,...,...,...,...,...,...,...
0,Stu_f8258e6b33109ea4808c004915145dd2,82.0,58.0,63.0,79.0,1016.0,696.0,359.0,227.0,62.0
0,Stu_fa1d7f2f99f036137482fbc04bab625b,208.0,39.0,51.0,45.0,287.0,1299.0,455.0,102.0,50.0
0,Stu_fb6121b7f70cc8dc2dca6a97e2c7cdc5,101.0,56.0,75.0,77.0,1009.0,1158.0,552.0,238.0,59.0
0,Stu_fd75420a601b7a43d13ea33ce657a2e1,109.0,4.0,0.0,0.0,5.0,19.0,3.0,6.0,22.0
0,Stu_ff13c22bdf5c4eb4fa87e03fe5d782ad,155.0,80.0,98.0,108.0,793.0,1667.0,601.0,244.0,134.0

In [91]:
# 4.2 接下来进行数据标准化：

# 归一化函数
max_min_scaler = lambda x : (x - np.min(x)) / (np.max(x) - np.min(x))

temp_df_behav = all_stu_behav.iloc[:, [1,2,3,4,5,6,7,8,9]].apply(max_min_scaler)
all_stu_behav_processed = pd.concat([all_stu_behav[['Anon Student Id']], temp_df_behav], axis = 1)
all_stu_behav_processed.to_csv('学生频次数据_归一化_0120.csv', encoding = 'utf8')
all_stu_behav_processed

,Anon Student Id,Answer,Axes,Choose-Principle,Choose-Sought,Equation,Explain-Further,NextStepHelp,Variable,Whats-Wrong
0,Stu_11eed491c49d08923078a99c3689faa6,0.345992,0.579545,0.548673,0.620968,0.215619,0.664640,0.607702,0.398374,0.267442
0,Stu_16d36e81d1d34630d27d8fd8b9d99d53,0.417722,0.647727,0.681416,0.701613,0.301313,1.000000,0.984356,0.574526,0.143411
0,Stu_1712d2d13ed773fddf0c9a59ad099b21,0.000000,0.034091,0.000000,0.000000,0.000000,0.003274,0.001203,0.000000,0.015504
0,Stu_18d58be83dc070054ca65038cc2293b4,0.291139,0.386364,0.292035,0.250000,0.107809,0.300281,0.297232,0.184282,0.131783
0,Stu_1a24bc4f1db0936c28f45176d3c425a7,0.063291,0.454545,0.407080,0.338710,0.319281,0.203929,0.297232,0.433604,0.356589
...,...,...,...,...,...,...,...,...,...,...
0,Stu_f8258e6b33109ea4808c004915145dd2,0.345992,0.659091,0.557522,0.637097,0.702142,0.325538,0.432010,0.615176,0.240310
0,Stu_fa1d7f2f99f036137482fbc04bab625b,0.877637,0.443182,0.451327,0.362903,0.198341,0.607577,0.547533,0.276423,0.193798
0,Stu_fb6121b7f70cc8dc2dca6a97e2c7cdc5,0.426160,0.636364,0.663717,0.620968,0.697305,0.541628,0.664260,0.644986,0.228682
0,Stu_fd75420a601b7a43d13ea33ce657a2e1,0.459916,0.045455,0.000000,0.000000,0.003455,0.008887,0.003610,0.016260,0.085271
0,Stu_ff13c22bdf5c4eb4fa87e03fe5d782ad,0.654008,0.909091,0.867257,0.870968,0.548030,0.779701,0.723225,0.661247,0.519380